/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_example_testdecode_RSDecoder */

#ifndef _Included_com_example_testdecode_RSDecoder
#define _Included_com_example_testdecode_RSDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testdecode_RSDecoder
 * Method:    addInt
 * Signature: (II)I
 */
extern int com_example_testdecode_RSDecoder_addInt(int, int);

/*
 * Class:     com_example_testdecode_RSDecoder
 * Method:    decodeRS
 * Signature: ([I[I)I
 */
extern int com_example_testdecode_RSDecoder_decodeRS(int *, int *);

#ifdef __cplusplus
}
#endif
#endif
